### ISSUE TITLE
Keys.js

### ISSUE THREAD

**Issue by troyam** [dfala/mailpants#1]
Missing keys.js

**Comment by dfala** [comment]
That's by design.

**Comment by troyam** [comment]
Can you help me with this?

**Comment by troyam** [comment]
I don't understand... sorry.

**Comment by dfala** [comment]
Files such as Keys.js may contain sensitive information with personal/company keys to third party products. You should create your own keys.

**Comment by troyam** [comment]
Sorry, I'm here again....
I understand how it works...
Can you show me the structure about keys.js?

Example: { secret : "xxx" , mandrill : "xxx" }

How I can set the keys...??
